module.exports = {
  READLINE_CELL_HAS_HOLE: 1,
  READLINE_UNKNOWN_ORE_AMOUNT: '?',
  READLINE_ENTITY_ALLIED_ROBOT: 0,
  READLINE_ENTITY_ENEMY_ROBOT: 1,
  READLINE_ENTITY_RADAR: 2,
  READLINE_ENTITY_MINE: 3
};
