module.exports = {
  ENTITY_ALLIED_ROBOT: 0,
  ENTITY_ENEMY_ROBOT: 1,
  ENTITY_RADAR: 2,
  ENTITY_MINE: 3,
  ITEM_NONE: -1,
  ITEM_HOLE: 1,
  ITEM_RADAR: 2,
  ITEM_MINE: 3,
  ITEM_ORE: 4,
  ITEM_ORE_UNKNOWN_AMOUNT: '?'
};
