module.exports = {
  READLINE_ORE_AMOUNT_UNKNOWN: '?',
  READLINE_ENTITY_ALLIED_ROBOT: 0,
  READLINE_ENTITY_ENEMY_ROBOT: 1,
  READLINE_ENTITY_RADAR: 2,
  READLINE_ENTITY_MINE: 3,
  READLINE_ITEM_NONE: -1,
  READLINE_ITEM_HOLE: 1,
  READLINE_ITEM_RADAR: 2,
  READLINE_ITEM_MINE: 3,
  READLINE_ITEM_ORE: 4
};
